# Tarea día 8
**Programación I**

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [12]:
import numpy as np
aleatorios = np.random.random((5, 5))
aleatorios


array([[0.47923738, 0.9118805 , 0.61160128, 0.1890884 , 0.9923572 ],
       [0.37210799, 0.83344813, 0.07648816, 0.54174648, 0.83251698],
       [0.56927111, 0.40786621, 0.77623067, 0.63876567, 0.7529063 ],
       [0.59654199, 0.00356336, 0.77215929, 0.15309234, 0.2613146 ],
       [0.17517249, 0.15165698, 0.24984271, 0.92925859, 0.31151145]])

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 


In [50]:
import numpy as np

#Crear dos matrices con ceros y unos
unos = np.ones((5, 2))
cero = np.zeros((5, 2))


# 1. convertir matrix en vector columnas

vector1 = unos[:,0:1]
vector2 = cero[:,0:1]

# 2. Ampliar a R3

a = np.ones((5, ))
b = np.zeros((5, ))
arraylist = [a, b]

outarr = np.ones((np.max([len(ps) for ps in arraylist]),len(arraylist)))*np.nan #define empty array
for i,c in enumerate(arraylist):  #populate columns
       outarr[:len(c),i]=c
outarr

#3. Concatenar vectores fila con vectores columna



array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios, donde cada columna sea una variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser una vector columna. 

In [5]:
# generar matriz con aleatorios
import numpy as np

ale = np.random.random((3, 3))


def evaluar(x,y,z):
    x = ale[0]
    y = ale[1]
    z = ale[2]
    solucion = [(2*x)+(3*y)+(z**2)]
    return solucion

evaluar(x,y,z)



[array([2.04716136, 4.5697351 , 2.8360525 ])]

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [123]:
a = int(2500)
n = 10000 #simulacion

x = np.random.random(n)*50 #datos aleatorios

y = np.random.random(n)*50 #datos aleatorios

#delimitacion de area

X = np.logical_and(15<x , x<35) 
Y = np.logical_and(15<y , y<35)
z = np.logical_and(X,Y)

#sumatoria de puntos fuera y dentro
inside_dots = z.sum()

area_objeto = area*(inside_dots/n)

area_objeto

26594.8179

## Ejercicio 5

### *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [86]:
import numpy as np

#array creation

np.arange(2, 10, dtype=float)





array([2., 3., 4., 5., 6., 7., 8., 9.])

In [75]:
#1 regresa un nuevo array de una shape y typo, sin las entradas

np.empty([2, 7], dtype=int)


array([[         0,          0,          0,          0,          0,
                 0,          0],
       [         0,          0,          0,          0,          0,
         824180736, 1563500588]])

In [77]:
#2 regresa un nuevo array conla misma shape y type 

b = np.array([[1., 2., 3.],[4.,5.,6.]])
np.empty_like(b)


array([[1., 1., 1.],
       [1., 1., 1.]])

In [80]:
#3 equivalente a identity function

np.eye(3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
#4 regresa una matriz solo de 1
np.ones((3, 3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
#5 regresa una matriz solo de 0
np.zeros((5,9))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [88]:
#6  regresa un arreglo con shape de una casilla llena
np.full((2, 2), [1, 2])

array([[1, 2],
       [1, 2]])

In [89]:
#7 crea un arregl
np.array([1, 2, 3])


array([1, 2, 3])

In [90]:
#8 convierte el input en un array
a = [1, 2]
np.asarray(a)

array([1, 2])

In [8]:
#9 convierte el input en un ndarray en orden de la columna mayor

x = np.arange(6).reshape(2,3)
np.ascontiguousarray(x, dtype=np.float32)

x.flags['C_CONTIGUOUS']



True

In [13]:
#10 ingresa un dato en el espacio de x


x = np.array([[8, 2], [3, 4]])
m = np.asmatrix(x)
x[0,0] = 7

m

matrix([[7, 2],
        [3, 4]])

In [17]:
#11 interpreta el buffer como un arrego unidimensional

s = b'hello world'
np.frombuffer(s, dtype='S1', count=5, offset=6)




array([b'w', b'o', b'r', b'l', b'd'], dtype='|S1')

In [18]:
#12 construye un array ejecutando una funcion sobre una coordenada

np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [19]:
#13 crea un nuevo array unidimensional desde un objeto iterable

iterable = (x*x for x in range(5))
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [22]:
#14 crea un array unidimensional desde data en texto en un string

np.fromstring('19, 226', dtype=int, sep=',')

array([ 19, 226])

In [26]:
#15  carga data desde un archivo de texto externo

from io import StringIO   # StringIO se comporta como si fuese un txt externo

c = StringIO(u"0 1\n2 3")
np.loadtxt(c)


array([[0., 1.],
       [2., 3.]])

In [27]:
#16 crea un record array desde un lista (flat) de arrays

x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])


(2, 'dd', 2.)


In [28]:
#17 crea a un recarray dsede una lista de records in forma de texto

r=np.core.records.fromrecords([(456,'dbe',1.2),(2,'de',1.3)],
names='col1,col2,col3')
print(r[0])

(456, 'dbe', 1.2)


In [29]:
#18 crea un array desde un archivo de data binario

from tempfile import TemporaryFile
a = np.empty(10,dtype='f8,i4,a5')
a


array([(1.06853059e-311,        130, b''),
       (0.00000000e+000,          0, b''),
       (1.38392195e-142, 1918989427, b'ted":'),
       (9.15558397e-072, 1412837677, b'21:28'),
       (2.58454752e-057,  576336952, b',"dep'),
       (3.29217421e+180, 1701666675, b't":tr'),
       (5.60482739e+199,  975332718, b'"aa46'),
       (1.24502100e-047, 1647586662, b'3b-a0'),
       (4.08416745e+179,  828586341, b'497",'),
       (9.97328607e-143, 1919230522, b'ror"}')],
      dtype=[('f0', '<f8'), ('f1', '<i4'), ('f2', 'S5')])

In [30]:
#19  regresa valores espaciados sin un intervalo

np.arange(3)



array([0, 1, 2])

In [34]:
#20  regresa valores espaciados sobre un intervalo especifico

np.linspace(2.0, 5.0, num=8)


array([2.        , 2.42857143, 2.85714286, 3.28571429, 3.71428571,
       4.14285714, 4.57142857, 5.        ])

In [35]:
#21 regresa numeros espaciados en escala logaritmica

np.logspace(2.0, 3.0, num=4)


array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [36]:
#22 regresa numeros espaciados en escala logaritmica( progresion geometrica)

np.geomspace(1, 1000, num=4, endpoint=False)


array([  1.        ,   5.62341325,  31.6227766 , 177.827941  ])

In [37]:
#23 regresa cordinate vectors desde cordinate vectors

nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
xv


array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [39]:
#24  instancia de nd_grid que regresa un denso multidimensional "meshgrid"

np.mgrid[0:5,0:5]


array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [40]:
#25 instancia de nd_grid que regresa un open multidimensional "meshgrid"
from numpy import ogrid
ogrid[-1:1:5j]


array([-1. , -0.5,  0. ,  0.5,  1. ])

In [41]:
#26 extrae una diagonal o un array diagonalizado
x = np.arange(9).reshape((3,3))
x
np.diag(x)

array([0, 4, 8])

In [42]:
#27  crea array bidimensional con el input flattenado como diagonal
np.diagflat([[1,2], [3,4]])



array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [45]:
#28 array con los unos hasta abajo 
np.tri(3, 5, 1, dtype=int)


array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [46]:
#29 regresa el triangulo inferior de una matriz
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)


array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [47]:
#30 regersa el triangulo superior de una matiz
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [50]:
#31 genera una matrix vandermode
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)


array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [53]:
#32 interpreta el input como una matriz

x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x[0,0] = 5
m

matrix([[5, 2],
        [3, 4]])

In [55]:
#33 crea una matriz desde un string

A = np.mat('1 1; 1 1')
B = np.mat('2 2; 2 2')
C = np.mat('3 4; 5 6')
D = np.mat('7 8; 9 0')

np.bmat([[A,B],[C,D]])

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [56]:
#34 copia los valores desde un array hacia otro
#numpy.copyto(dst, src, casting='same_kind', where=True)

In [57]:
#35 regresa el shape de un array
np.shape(np.eye(3))

(3, 3)

In [58]:
#36 da un nuevo shape a un array que no cambia datos

a = np.arange(6).reshape((3, 2))
a
np.reshape(a, (2, 3)) # C-like index ordering


array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
#37 regresa un array contiguous flattened

x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)


array([1, 2, 3, 4, 5, 6])

In [60]:
#38 regresa la copia d eun array collapsado en una dimension
x = np.arange(1, 7).reshape(2, 3)
x.flat[3]

x


array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
#39 regresa una copia de un array collapsado en una dimension
a = np.array([[1,2,5], [9,3,4]])
a.flatten()

array([1, 2, 5, 9, 3, 4])

In [63]:
#40 mueve los ejes de un array en nuevas posiciones
x = np.zeros((3, 4, 5))
np.moveaxis(x, 0, -1).shape

(4, 5, 3)

In [64]:
#41 rola el eje al reves, hasta que asiente en la nueva posicion
a = np.ones((3,4,5,6))
np.rollaxis(a, 3, 1).shape


(3, 6, 4, 5)

In [65]:
#42 transpone el array
x = np.array([[1.,2.],[3.,4.]])
x.T

array([[1., 3.],
       [2., 4.]])

In [66]:
# 43 permuta ls ejes de un array, regresa la modificada
x = np.arange(4).reshape((2,2))
np.transpose(x)


array([[0, 2],
       [1, 3]])

In [67]:
#44 ve los inputs como array con almenos tres dimensiones
np.atleast_3d(3.0)


array([[[3.]]])

In [69]:
#45 produce un ojeto que hace copia con un broadcasting
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
out = np.empty(b.shape)
out.flat = [u+v for (u,v) in b]
out


array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [70]:
#46 broadcastea cualquier numero de array encontra de ellos mismos
x = np.array([[1,2,3]])
y = np.array([[4],[5]])
np.broadcast_arrays(x, y)


[array([[1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5]])]

In [73]:
#47 remueve una dimension en la entrada desde el shape de un array
x = np.array([[[0], [1], [2]]])
print(x.shape)
np.squeeze(x).shape


(1, 3, 1)


(3,)

In [74]:
#48 convierte el input a un array
a = [1, 2]
np.asarray(a)


array([1, 2])

In [75]:
#49 convierte el inputo a un narray, pero pasa ndarray sobre las subclaes
a = [1, 2]
np.asanyarray(a)


array([1, 2])

In [76]:
#50 interpreta el input como matrix

x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x[0,0] = 5
m



matrix([[5, 2],
        [3, 4]])

In [78]:
#51 convierte un array de tamaño 1 a su escalar equivalente
np.asscalar(np.array([89]))

89

In [79]:
#52 regresa un ndarray de un tipo que satisface el requerido


x = np.arange(6).reshape(2,3)
x.flags
C_CONTIGUOUS : True
F_CONTIGUOUS : False
OWNDATA : False
WRITEABLE : True
ALIGNED : True
WRITEBACKIFCOPY : False
UPDATEIFCOPY : False

y = np.require(x, dtype=np.float32, requirements=['A', 'O', 'W', 'F'])
y.flags


  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [80]:
#53 concatena un secuencia de arrays junto a un eje existente
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
#54 apila array unidimensionales en bidimensionales
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))


array([[1, 2],
       [2, 3],
       [3, 4]])

In [82]:
#55 apila array horizontalmente
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))


array([1, 2, 3, 2, 3, 4])

In [84]:
#56 ensambla un nd-array desde una lista nesteada de blocks
A = np.eye(2) * 2
B = np.eye(3) * 3
np.block([[A,np.zeros((2, 3))],[np.ones((3, 2)),B]])
np.block([1, 2, 3])

array([1, 2, 3])

In [85]:
#57 separa un array en multiples subarrays
x = np.arange(8.0)
np.array_split(x, 3)


[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [86]:
#58 separa un array en multiples subarrays de igual tamaño
x = np.arange(8.0).reshape(2, 2, 2)
x
np.hsplit(x, 2)

[array([[[0., 1.]],
 
        [[4., 5.]]]), array([[[2., 3.]],
 
        [[6., 7.]]])]

In [88]:
#59 hace un array repitiendo A el numero de veces pedido
a = np.array([0, 1, 2])
np.tile(a, 5)

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])

In [89]:
#60 regresa un nuevo array con una shape especifica
a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))


array([[0, 1, 2],
       [3, 0, 1]])

In [90]:
#61 revierte el orden de los elementos en un array dado el eje
A = np.arange(8).reshape((2,2,2))
A
np.flip(A, 0)


array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [91]:
#61  da un nuevo shape hacia un array sin cambiar su data
a = np.arange(6).reshape((3, 2))
np.reshape(a, (2, 3)) 


array([[0, 1, 2],
       [3, 4, 5]])

In [92]:
#62 computa de bit-wise AND dos elementos de un array wise

np.bitwise_and(13, 17)


1

In [93]:
np.bitwise_and(14, 13)


12

In [94]:
#63 empaqueta el elemento de un array binario en un array unitario

a = np.array([[[1,0,1],[0,1,0]],[[1,1,0],[0,0,1]]])
b = np.packbits(a, axis=-1)
b


array([[[160],
        [ 64]],

       [[192],
        [ 32]]], dtype=uint8)

In [96]:
#64 regresa una representacion de el numero input como string
np.binary_repr(89)


'1011001'

In [98]:
#64 regresa la suma de dos array
x1 = np.array([1,2])
x2 = np.array([1,2])
np.add(x1,x2)

array([2, 4])

In [100]:
#65 regresa la multiplicacion de dos array
x1 = np.array([1,2])
x2 = np.array([1,2])
np.multiply(x1,x2)


array([1, 4])

In [102]:
#66 llama str.decode element-wise

c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
np.char.encode(c, encoding='cp037')


array([b'\x81\xc1\x81\xc1\x81\xc1', b'@@\x81\xc1@@',
       b'\x81\x82\xc2\xc1\xc2\x82\x81'], dtype='|S7')

In [103]:
#67 regresa un array con los elementos cnvertidos a minisculas
c = np.array(['A1B C', '1BCA', 'BCA1']); c

np.char.lower(c)


array(['a1b c', '1bca', 'bca1'], dtype='<U5')

In [108]:
#68 para cada elemento in a, regresa una copia con los caracteres removidos

c = np.array(['aAaAaA', 'abBABba'], dtype='S7'); c

np.char.rstrip(c, b'a')


array([b'aAaAaA', b'abBABb'], dtype='|S7')

In [110]:
#69 para cada elemento in a, regresa una copia con los elementos (inicial y final)
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])

np.char.strip(c, 'a')


array(['AaAaA', '  aA  ', 'bBABb'], dtype='<U7')

In [111]:
#70 regresa un una copia del string con mayusculas e viceversa
c=np.array(['a1B c','1b Ca','b Ca1','cA1b'],'S5'); c

np.char.swapcase(c)


array([b'A1b C', b'1B cA', b'B cA1', b'Ca1B'], dtype='|S5')

In [112]:
#71 recresa (x1==x2) element-wise
x1 = np.array([1,2])
x2 = np.array([1,2])
np.equal(x1,x2)

array([ True,  True])

In [113]:
#72 regresa (x1 != x2)
x1 = np.array([1,2])
x2 = np.array([1,2])
np.not_equal(x1,x2)

array([False, False])

In [114]:
#73 regresa un array con el numero de ocurrencias en los substrings
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])

np.char.count(c, 'A')

array([3, 1, 1])

In [118]:
#guardar y cargar
#numpy.save(file, arr, allow_pickle=True, fix_imports=True


from tempfile import TemporaryFile
outfile = TemporaryFile()
x = np.arange(10)
np.save(outfile, x)


_ = outfile.seek(0) # se utiliza para simular apertura y cierre de archivos
np.load(outfile)

with open('test.npy', 'wb') as f: 
    np.save(f, np.array([1, 2]))
    np.save(f, np.array([1, 3]))
with open('test.npy', 'rb') as f:
    a = np.load(f)
    b = np.load(f)
print(a, b)




[1 2] [1 3]


4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [ ]:
def estimacionMCO:
    X=np.
    betas